#!/bin/sh

python "$DEV/personal/obsidian-cli/app/obsidian_cli.py" "$@"




##!/usr/bin/python3
## -*- coding: utf-8 -*-
#import os
#import re
#import sys
#import pathlib
#import json
#
#
#def main() -> int:
#    return 0
#
#
#if __name__ == "__main__":
#    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
#    sys.exit(main())
