#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
import subprocess
import urllib.parse


def encode_tag(tag: str) -> str:
    return urllib.parse.quote_plus(f"tag:#{tag}")


def main() -> int:
    if len(sys.argv) != 2:
        sys.stdout.write("usage: cmd tag[/sub-tag]\n")
        return 1

    query = sys.argv[1]
    sys.argv.clear()
    sys.argv.append("$DOTFILES/bin/obsidian_vault_id")
    out = subprocess.run(["obsidian_vault_id"], capture_output=True)
    if out.returncode:
        return 1

    vault_id = out.stdout.decode("utf-8")
    uri = f"obsidian://search?vault={vault_id}&query={encode_tag(query)}"
    subprocess.run(["open", uri])
    return 0


if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    sys.exit(main())
