#!/usr/bin/python3
# -*- coding: utf-8 -*-
import os
import re
import sys
import pathlib
import subprocess
import urllib.parse


def encode_tag(tag: str) -> str:
    return urllib.parse.quote(f"{tag}")


def main() -> int:
    if len(sys.argv) != 1:
        sys.stdout.write("usage: cmd\n")
        return 1

    sys.argv.append(f"{os.getenv('DOTFILES')}/bin/obsidian_vault_id")
    out = subprocess.run(["obsidian_vault_id"], capture_output=True)
    if out.returncode:
        return 1

    vault_id = out.stdout.decode("utf-8")
    obsidian_vault = pathlib.Path(s if (s := os.getenv("OBSIDIAN_VAULT")) else "")
    if not obsidian_vault.exists():
        sys.stdout.write("obsidian_vault not found\n")
        return 1

    stack_file = "3) Resources/Stack.md"
    resource = obsidian_vault / stack_file
    if not resource.exists():
        sys.stdout.write("resource could not be found on disk\n")
        return 1

    uri = f"obsidian://open?vault={vault_id}&file={encode_tag(stack_file)}"
    subprocess.run(["open", uri])
    return 0


if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    sys.exit(main())
